DROP TABLE IF EXISTS acc_user;
CREATE TABLE acc_user(
	id INT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(128) NOT NULL DEFAULT '',
	age SMALLINT NOT NULL DEFAULT -1,
	`password` CHAR(32) NOT NULL DEFAULT ''
);