package com.accumulate.mapper;

import com.accumulate.entity.PasswordPolicyConstraint;
import com.accumulate.entity.PasswordPolicyConstraintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PasswordPolicyConstraintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_constraint
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    long countByExample(PasswordPolicyConstraintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_constraint
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    int deleteByExample(PasswordPolicyConstraintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_constraint
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_constraint
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    int insert(PasswordPolicyConstraint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_constraint
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    int insertSelective(PasswordPolicyConstraint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_constraint
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    List<PasswordPolicyConstraint> selectByExample(PasswordPolicyConstraintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_constraint
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    PasswordPolicyConstraint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_constraint
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") PasswordPolicyConstraint record, @Param("example") PasswordPolicyConstraintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_constraint
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    int updateByExample(@Param("record") PasswordPolicyConstraint record, @Param("example") PasswordPolicyConstraintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_constraint
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    int updateByPrimaryKeySelective(PasswordPolicyConstraint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_constraint
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    int updateByPrimaryKey(PasswordPolicyConstraint record);
}