package com.accumulate.mapper;

import com.accumulate.entity.PasswordPolicyRetry;
import com.accumulate.entity.PasswordPolicyRetryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PasswordPolicyRetryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_retry
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    long countByExample(PasswordPolicyRetryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_retry
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    int deleteByExample(PasswordPolicyRetryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_retry
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_retry
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    int insert(PasswordPolicyRetry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_retry
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    int insertSelective(PasswordPolicyRetry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_retry
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    List<PasswordPolicyRetry> selectByExample(PasswordPolicyRetryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_retry
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    PasswordPolicyRetry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_retry
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") PasswordPolicyRetry record, @Param("example") PasswordPolicyRetryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_retry
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    int updateByExample(@Param("record") PasswordPolicyRetry record, @Param("example") PasswordPolicyRetryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_retry
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    int updateByPrimaryKeySelective(PasswordPolicyRetry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_retry
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    int updateByPrimaryKey(PasswordPolicyRetry record);
}