package com.accumulate.mapper;

import com.accumulate.entity.PasswordPolicy;
import com.accumulate.entity.PasswordPolicyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PasswordPolicyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    long countByExample(PasswordPolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    int deleteByExample(PasswordPolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    int insert(PasswordPolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    int insertSelective(PasswordPolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    List<PasswordPolicy> selectByExampleWithBLOBs(PasswordPolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    List<PasswordPolicy> selectByExample(PasswordPolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    PasswordPolicy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    int updateByExampleSelective(@Param("record") PasswordPolicy record, @Param("example") PasswordPolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") PasswordPolicy record, @Param("example") PasswordPolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    int updateByExample(@Param("record") PasswordPolicy record, @Param("example") PasswordPolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    int updateByPrimaryKeySelective(PasswordPolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(PasswordPolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    int updateByPrimaryKey(PasswordPolicy record);
}