package com.accumulate.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PasswordPolicyConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    public PasswordPolicyConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("enable is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("enable is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Boolean value) {
            addCriterion("enable =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Boolean value) {
            addCriterion("enable <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Boolean value) {
            addCriterion("enable >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enable >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Boolean value) {
            addCriterion("enable <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("enable <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Boolean> values) {
            addCriterion("enable in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Boolean> values) {
            addCriterion("enable not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("enable between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enable not between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andBannedIsNull() {
            addCriterion("banned is null");
            return (Criteria) this;
        }

        public Criteria andBannedIsNotNull() {
            addCriterion("banned is not null");
            return (Criteria) this;
        }

        public Criteria andBannedEqualTo(Boolean value) {
            addCriterion("banned =", value, "banned");
            return (Criteria) this;
        }

        public Criteria andBannedNotEqualTo(Boolean value) {
            addCriterion("banned <>", value, "banned");
            return (Criteria) this;
        }

        public Criteria andBannedGreaterThan(Boolean value) {
            addCriterion("banned >", value, "banned");
            return (Criteria) this;
        }

        public Criteria andBannedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("banned >=", value, "banned");
            return (Criteria) this;
        }

        public Criteria andBannedLessThan(Boolean value) {
            addCriterion("banned <", value, "banned");
            return (Criteria) this;
        }

        public Criteria andBannedLessThanOrEqualTo(Boolean value) {
            addCriterion("banned <=", value, "banned");
            return (Criteria) this;
        }

        public Criteria andBannedIn(List<Boolean> values) {
            addCriterion("banned in", values, "banned");
            return (Criteria) this;
        }

        public Criteria andBannedNotIn(List<Boolean> values) {
            addCriterion("banned not in", values, "banned");
            return (Criteria) this;
        }

        public Criteria andBannedBetween(Boolean value1, Boolean value2) {
            addCriterion("banned between", value1, value2, "banned");
            return (Criteria) this;
        }

        public Criteria andBannedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("banned not between", value1, value2, "banned");
            return (Criteria) this;
        }

        public Criteria andBannedUrlIsNull() {
            addCriterion("banned_url is null");
            return (Criteria) this;
        }

        public Criteria andBannedUrlIsNotNull() {
            addCriterion("banned_url is not null");
            return (Criteria) this;
        }

        public Criteria andBannedUrlEqualTo(String value) {
            addCriterion("banned_url =", value, "bannedUrl");
            return (Criteria) this;
        }

        public Criteria andBannedUrlNotEqualTo(String value) {
            addCriterion("banned_url <>", value, "bannedUrl");
            return (Criteria) this;
        }

        public Criteria andBannedUrlGreaterThan(String value) {
            addCriterion("banned_url >", value, "bannedUrl");
            return (Criteria) this;
        }

        public Criteria andBannedUrlGreaterThanOrEqualTo(String value) {
            addCriterion("banned_url >=", value, "bannedUrl");
            return (Criteria) this;
        }

        public Criteria andBannedUrlLessThan(String value) {
            addCriterion("banned_url <", value, "bannedUrl");
            return (Criteria) this;
        }

        public Criteria andBannedUrlLessThanOrEqualTo(String value) {
            addCriterion("banned_url <=", value, "bannedUrl");
            return (Criteria) this;
        }

        public Criteria andBannedUrlLike(String value) {
            addCriterion("banned_url like", value, "bannedUrl");
            return (Criteria) this;
        }

        public Criteria andBannedUrlNotLike(String value) {
            addCriterion("banned_url not like", value, "bannedUrl");
            return (Criteria) this;
        }

        public Criteria andBannedUrlIn(List<String> values) {
            addCriterion("banned_url in", values, "bannedUrl");
            return (Criteria) this;
        }

        public Criteria andBannedUrlNotIn(List<String> values) {
            addCriterion("banned_url not in", values, "bannedUrl");
            return (Criteria) this;
        }

        public Criteria andBannedUrlBetween(String value1, String value2) {
            addCriterion("banned_url between", value1, value2, "bannedUrl");
            return (Criteria) this;
        }

        public Criteria andBannedUrlNotBetween(String value1, String value2) {
            addCriterion("banned_url not between", value1, value2, "bannedUrl");
            return (Criteria) this;
        }

        public Criteria andConstraintIdIsNull() {
            addCriterion("constraint_id is null");
            return (Criteria) this;
        }

        public Criteria andConstraintIdIsNotNull() {
            addCriterion("constraint_id is not null");
            return (Criteria) this;
        }

        public Criteria andConstraintIdEqualTo(Integer value) {
            addCriterion("constraint_id =", value, "constraintId");
            return (Criteria) this;
        }

        public Criteria andConstraintIdNotEqualTo(Integer value) {
            addCriterion("constraint_id <>", value, "constraintId");
            return (Criteria) this;
        }

        public Criteria andConstraintIdGreaterThan(Integer value) {
            addCriterion("constraint_id >", value, "constraintId");
            return (Criteria) this;
        }

        public Criteria andConstraintIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("constraint_id >=", value, "constraintId");
            return (Criteria) this;
        }

        public Criteria andConstraintIdLessThan(Integer value) {
            addCriterion("constraint_id <", value, "constraintId");
            return (Criteria) this;
        }

        public Criteria andConstraintIdLessThanOrEqualTo(Integer value) {
            addCriterion("constraint_id <=", value, "constraintId");
            return (Criteria) this;
        }

        public Criteria andConstraintIdIn(List<Integer> values) {
            addCriterion("constraint_id in", values, "constraintId");
            return (Criteria) this;
        }

        public Criteria andConstraintIdNotIn(List<Integer> values) {
            addCriterion("constraint_id not in", values, "constraintId");
            return (Criteria) this;
        }

        public Criteria andConstraintIdBetween(Integer value1, Integer value2) {
            addCriterion("constraint_id between", value1, value2, "constraintId");
            return (Criteria) this;
        }

        public Criteria andConstraintIdNotBetween(Integer value1, Integer value2) {
            addCriterion("constraint_id not between", value1, value2, "constraintId");
            return (Criteria) this;
        }

        public Criteria andExpirationIdIsNull() {
            addCriterion("expiration_id is null");
            return (Criteria) this;
        }

        public Criteria andExpirationIdIsNotNull() {
            addCriterion("expiration_id is not null");
            return (Criteria) this;
        }

        public Criteria andExpirationIdEqualTo(Integer value) {
            addCriterion("expiration_id =", value, "expirationId");
            return (Criteria) this;
        }

        public Criteria andExpirationIdNotEqualTo(Integer value) {
            addCriterion("expiration_id <>", value, "expirationId");
            return (Criteria) this;
        }

        public Criteria andExpirationIdGreaterThan(Integer value) {
            addCriterion("expiration_id >", value, "expirationId");
            return (Criteria) this;
        }

        public Criteria andExpirationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("expiration_id >=", value, "expirationId");
            return (Criteria) this;
        }

        public Criteria andExpirationIdLessThan(Integer value) {
            addCriterion("expiration_id <", value, "expirationId");
            return (Criteria) this;
        }

        public Criteria andExpirationIdLessThanOrEqualTo(Integer value) {
            addCriterion("expiration_id <=", value, "expirationId");
            return (Criteria) this;
        }

        public Criteria andExpirationIdIn(List<Integer> values) {
            addCriterion("expiration_id in", values, "expirationId");
            return (Criteria) this;
        }

        public Criteria andExpirationIdNotIn(List<Integer> values) {
            addCriterion("expiration_id not in", values, "expirationId");
            return (Criteria) this;
        }

        public Criteria andExpirationIdBetween(Integer value1, Integer value2) {
            addCriterion("expiration_id between", value1, value2, "expirationId");
            return (Criteria) this;
        }

        public Criteria andExpirationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("expiration_id not between", value1, value2, "expirationId");
            return (Criteria) this;
        }

        public Criteria andRetryIdIsNull() {
            addCriterion("retry_id is null");
            return (Criteria) this;
        }

        public Criteria andRetryIdIsNotNull() {
            addCriterion("retry_id is not null");
            return (Criteria) this;
        }

        public Criteria andRetryIdEqualTo(Integer value) {
            addCriterion("retry_id =", value, "retryId");
            return (Criteria) this;
        }

        public Criteria andRetryIdNotEqualTo(Integer value) {
            addCriterion("retry_id <>", value, "retryId");
            return (Criteria) this;
        }

        public Criteria andRetryIdGreaterThan(Integer value) {
            addCriterion("retry_id >", value, "retryId");
            return (Criteria) this;
        }

        public Criteria andRetryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("retry_id >=", value, "retryId");
            return (Criteria) this;
        }

        public Criteria andRetryIdLessThan(Integer value) {
            addCriterion("retry_id <", value, "retryId");
            return (Criteria) this;
        }

        public Criteria andRetryIdLessThanOrEqualTo(Integer value) {
            addCriterion("retry_id <=", value, "retryId");
            return (Criteria) this;
        }

        public Criteria andRetryIdIn(List<Integer> values) {
            addCriterion("retry_id in", values, "retryId");
            return (Criteria) this;
        }

        public Criteria andRetryIdNotIn(List<Integer> values) {
            addCriterion("retry_id not in", values, "retryId");
            return (Criteria) this;
        }

        public Criteria andRetryIdBetween(Integer value1, Integer value2) {
            addCriterion("retry_id between", value1, value2, "retryId");
            return (Criteria) this;
        }

        public Criteria andRetryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("retry_id not between", value1, value2, "retryId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(Integer value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(Integer value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(Integer value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(Integer value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(Integer value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<Integer> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<Integer> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(Integer value1, Integer value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(Integer value1, Integer value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(Integer value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(Integer value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(Integer value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(Integer value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(Integer value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<Integer> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<Integer> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(Integer value1, Integer value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(Integer value1, Integer value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 05 16:28:56 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table acc_password_policy_config
     *
     * @mbg.generated Thu Jan 05 16:28:56 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}