package com.accumulate.entity;

public class PasswordPolicyConstraint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_constraint.id
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_constraint.enable
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_constraint.min
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Integer min;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_constraint.max
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Integer max;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_constraint.max_repeat_character
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Integer maxRepeatCharacter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_constraint.min_non_alphanumeric
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Integer minNonAlphanumeric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_constraint.min_digits
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Integer minDigits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_constraint.min_lowercase
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Integer minLowercase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_constraint.min_uppercase
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Integer minUppercase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_constraint.not_blank
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Boolean notBlank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_constraint.id
     *
     * @return the value of acc_password_policy_constraint.id
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_constraint.id
     *
     * @param id the value for acc_password_policy_constraint.id
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_constraint.enable
     *
     * @return the value of acc_password_policy_constraint.enable
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_constraint.enable
     *
     * @param enable the value for acc_password_policy_constraint.enable
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_constraint.min
     *
     * @return the value of acc_password_policy_constraint.min
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Integer getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_constraint.min
     *
     * @param min the value for acc_password_policy_constraint.min
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setMin(Integer min) {
        this.min = min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_constraint.max
     *
     * @return the value of acc_password_policy_constraint.max
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Integer getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_constraint.max
     *
     * @param max the value for acc_password_policy_constraint.max
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setMax(Integer max) {
        this.max = max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_constraint.max_repeat_character
     *
     * @return the value of acc_password_policy_constraint.max_repeat_character
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Integer getMaxRepeatCharacter() {
        return maxRepeatCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_constraint.max_repeat_character
     *
     * @param maxRepeatCharacter the value for acc_password_policy_constraint.max_repeat_character
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setMaxRepeatCharacter(Integer maxRepeatCharacter) {
        this.maxRepeatCharacter = maxRepeatCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_constraint.min_non_alphanumeric
     *
     * @return the value of acc_password_policy_constraint.min_non_alphanumeric
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Integer getMinNonAlphanumeric() {
        return minNonAlphanumeric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_constraint.min_non_alphanumeric
     *
     * @param minNonAlphanumeric the value for acc_password_policy_constraint.min_non_alphanumeric
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setMinNonAlphanumeric(Integer minNonAlphanumeric) {
        this.minNonAlphanumeric = minNonAlphanumeric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_constraint.min_digits
     *
     * @return the value of acc_password_policy_constraint.min_digits
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Integer getMinDigits() {
        return minDigits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_constraint.min_digits
     *
     * @param minDigits the value for acc_password_policy_constraint.min_digits
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setMinDigits(Integer minDigits) {
        this.minDigits = minDigits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_constraint.min_lowercase
     *
     * @return the value of acc_password_policy_constraint.min_lowercase
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Integer getMinLowercase() {
        return minLowercase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_constraint.min_lowercase
     *
     * @param minLowercase the value for acc_password_policy_constraint.min_lowercase
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setMinLowercase(Integer minLowercase) {
        this.minLowercase = minLowercase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_constraint.min_uppercase
     *
     * @return the value of acc_password_policy_constraint.min_uppercase
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Integer getMinUppercase() {
        return minUppercase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_constraint.min_uppercase
     *
     * @param minUppercase the value for acc_password_policy_constraint.min_uppercase
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setMinUppercase(Integer minUppercase) {
        this.minUppercase = minUppercase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_constraint.not_blank
     *
     * @return the value of acc_password_policy_constraint.not_blank
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Boolean getNotBlank() {
        return notBlank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_constraint.not_blank
     *
     * @param notBlank the value for acc_password_policy_constraint.not_blank
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setNotBlank(Boolean notBlank) {
        this.notBlank = notBlank;
    }
}