package com.accumulate.entity;

import java.util.Date;

public class PasswordPolicy extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy.id
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy.create_time
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy.create_by
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy.update_time
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy.update_by
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy.general
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private String general;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy.constraint
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private String constraint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy.expiration
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private String expiration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy.expireMessage
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private String expiremessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy.retry
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private String retry;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy.id
     *
     * @return the value of acc_password_policy.id
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy.id
     *
     * @param id the value for acc_password_policy.id
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy.create_time
     *
     * @return the value of acc_password_policy.create_time
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy.create_time
     *
     * @param createTime the value for acc_password_policy.create_time
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy.create_by
     *
     * @return the value of acc_password_policy.create_by
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy.create_by
     *
     * @param createBy the value for acc_password_policy.create_by
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy.update_time
     *
     * @return the value of acc_password_policy.update_time
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy.update_time
     *
     * @param updateTime the value for acc_password_policy.update_time
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy.update_by
     *
     * @return the value of acc_password_policy.update_by
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy.update_by
     *
     * @param updateBy the value for acc_password_policy.update_by
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy.general
     *
     * @return the value of acc_password_policy.general
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public String getGeneral() {
        return general;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy.general
     *
     * @param general the value for acc_password_policy.general
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setGeneral(String general) {
        this.general = general == null ? null : general.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy.constraint
     *
     * @return the value of acc_password_policy.constraint
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public String getConstraint() {
        return constraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy.constraint
     *
     * @param constraint the value for acc_password_policy.constraint
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setConstraint(String constraint) {
        this.constraint = constraint == null ? null : constraint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy.expiration
     *
     * @return the value of acc_password_policy.expiration
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public String getExpiration() {
        return expiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy.expiration
     *
     * @param expiration the value for acc_password_policy.expiration
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setExpiration(String expiration) {
        this.expiration = expiration == null ? null : expiration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy.expireMessage
     *
     * @return the value of acc_password_policy.expireMessage
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public String getExpiremessage() {
        return expiremessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy.expireMessage
     *
     * @param expiremessage the value for acc_password_policy.expireMessage
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setExpiremessage(String expiremessage) {
        this.expiremessage = expiremessage == null ? null : expiremessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy.retry
     *
     * @return the value of acc_password_policy.retry
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public String getRetry() {
        return retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy.retry
     *
     * @param retry the value for acc_password_policy.retry
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setRetry(String retry) {
        this.retry = retry == null ? null : retry.trim();
    }
}