package com.accumulate.entity;

public class PasswordPolicyConfig extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_config.name
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_config.description
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_config.enable
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_config.banned
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    private Boolean banned;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_config.banned_url
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    private String bannedUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_config.constraint_id
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    private Integer constraintId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_config.expiration_id
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    private Integer expirationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_config.retry_id
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    private Integer retryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_config.name
     *
     * @return the value of acc_password_policy_config.name
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_config.name
     *
     * @param name the value for acc_password_policy_config.name
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_config.description
     *
     * @return the value of acc_password_policy_config.description
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_config.description
     *
     * @param description the value for acc_password_policy_config.description
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_config.enable
     *
     * @return the value of acc_password_policy_config.enable
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_config.enable
     *
     * @param enable the value for acc_password_policy_config.enable
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_config.banned
     *
     * @return the value of acc_password_policy_config.banned
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public Boolean getBanned() {
        return banned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_config.banned
     *
     * @param banned the value for acc_password_policy_config.banned
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public void setBanned(Boolean banned) {
        this.banned = banned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_config.banned_url
     *
     * @return the value of acc_password_policy_config.banned_url
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public String getBannedUrl() {
        return bannedUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_config.banned_url
     *
     * @param bannedUrl the value for acc_password_policy_config.banned_url
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public void setBannedUrl(String bannedUrl) {
        this.bannedUrl = bannedUrl == null ? null : bannedUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_config.constraint_id
     *
     * @return the value of acc_password_policy_config.constraint_id
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public Integer getConstraintId() {
        return constraintId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_config.constraint_id
     *
     * @param constraintId the value for acc_password_policy_config.constraint_id
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public void setConstraintId(Integer constraintId) {
        this.constraintId = constraintId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_config.expiration_id
     *
     * @return the value of acc_password_policy_config.expiration_id
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public Integer getExpirationId() {
        return expirationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_config.expiration_id
     *
     * @param expirationId the value for acc_password_policy_config.expiration_id
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public void setExpirationId(Integer expirationId) {
        this.expirationId = expirationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_config.retry_id
     *
     * @return the value of acc_password_policy_config.retry_id
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public Integer getRetryId() {
        return retryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_config.retry_id
     *
     * @param retryId the value for acc_password_policy_config.retry_id
     *
     * @mbg.generated Fri Jan 06 11:30:00 CST 2017
     */
    public void setRetryId(Integer retryId) {
        this.retryId = retryId;
    }
}