package com.accumulate.entity;

public class PasswordPolicyRetry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_retry.id
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_retry.enable
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_retry.num
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_retry.lock_time
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    private Integer lockTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_retry.id
     *
     * @return the value of acc_password_policy_retry.id
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_retry.id
     *
     * @param id the value for acc_password_policy_retry.id
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_retry.enable
     *
     * @return the value of acc_password_policy_retry.enable
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_retry.enable
     *
     * @param enable the value for acc_password_policy_retry.enable
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_retry.num
     *
     * @return the value of acc_password_policy_retry.num
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_retry.num
     *
     * @param num the value for acc_password_policy_retry.num
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_retry.lock_time
     *
     * @return the value of acc_password_policy_retry.lock_time
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    public Integer getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_retry.lock_time
     *
     * @param lockTime the value for acc_password_policy_retry.lock_time
     *
     * @mbg.generated Fri Jan 06 11:29:43 CST 2017
     */
    public void setLockTime(Integer lockTime) {
        this.lockTime = lockTime;
    }
}