package com.accumulate.entity;

public class PasswordPolicyExpiration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_expiration.id
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_expiration.enable
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_expiration.expired_day
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Integer expiredDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_expiration.waring_before_day
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Integer waringBeforeDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_expiration.waring_action
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private Integer waringAction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_expiration.subject
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_expiration.email_expiring_message
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private String emailExpiringMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_expiration.email_expired_message
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private String emailExpiredMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_expiration.sms_expiring_message
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private String smsExpiringMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_password_policy_expiration.sms_expired_message
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    private String smsExpiredMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_expiration.id
     *
     * @return the value of acc_password_policy_expiration.id
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_expiration.id
     *
     * @param id the value for acc_password_policy_expiration.id
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_expiration.enable
     *
     * @return the value of acc_password_policy_expiration.enable
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_expiration.enable
     *
     * @param enable the value for acc_password_policy_expiration.enable
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_expiration.expired_day
     *
     * @return the value of acc_password_policy_expiration.expired_day
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Integer getExpiredDay() {
        return expiredDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_expiration.expired_day
     *
     * @param expiredDay the value for acc_password_policy_expiration.expired_day
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setExpiredDay(Integer expiredDay) {
        this.expiredDay = expiredDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_expiration.waring_before_day
     *
     * @return the value of acc_password_policy_expiration.waring_before_day
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Integer getWaringBeforeDay() {
        return waringBeforeDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_expiration.waring_before_day
     *
     * @param waringBeforeDay the value for acc_password_policy_expiration.waring_before_day
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setWaringBeforeDay(Integer waringBeforeDay) {
        this.waringBeforeDay = waringBeforeDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_expiration.waring_action
     *
     * @return the value of acc_password_policy_expiration.waring_action
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public Integer getWaringAction() {
        return waringAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_expiration.waring_action
     *
     * @param waringAction the value for acc_password_policy_expiration.waring_action
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setWaringAction(Integer waringAction) {
        this.waringAction = waringAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_expiration.subject
     *
     * @return the value of acc_password_policy_expiration.subject
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_expiration.subject
     *
     * @param subject the value for acc_password_policy_expiration.subject
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_expiration.email_expiring_message
     *
     * @return the value of acc_password_policy_expiration.email_expiring_message
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public String getEmailExpiringMessage() {
        return emailExpiringMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_expiration.email_expiring_message
     *
     * @param emailExpiringMessage the value for acc_password_policy_expiration.email_expiring_message
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setEmailExpiringMessage(String emailExpiringMessage) {
        this.emailExpiringMessage = emailExpiringMessage == null ? null : emailExpiringMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_expiration.email_expired_message
     *
     * @return the value of acc_password_policy_expiration.email_expired_message
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public String getEmailExpiredMessage() {
        return emailExpiredMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_expiration.email_expired_message
     *
     * @param emailExpiredMessage the value for acc_password_policy_expiration.email_expired_message
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setEmailExpiredMessage(String emailExpiredMessage) {
        this.emailExpiredMessage = emailExpiredMessage == null ? null : emailExpiredMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_expiration.sms_expiring_message
     *
     * @return the value of acc_password_policy_expiration.sms_expiring_message
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public String getSmsExpiringMessage() {
        return smsExpiringMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_expiration.sms_expiring_message
     *
     * @param smsExpiringMessage the value for acc_password_policy_expiration.sms_expiring_message
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setSmsExpiringMessage(String smsExpiringMessage) {
        this.smsExpiringMessage = smsExpiringMessage == null ? null : smsExpiringMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_password_policy_expiration.sms_expired_message
     *
     * @return the value of acc_password_policy_expiration.sms_expired_message
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public String getSmsExpiredMessage() {
        return smsExpiredMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_password_policy_expiration.sms_expired_message
     *
     * @param smsExpiredMessage the value for acc_password_policy_expiration.sms_expired_message
     *
     * @mbg.generated Thu Jan 05 16:45:06 CST 2017
     */
    public void setSmsExpiredMessage(String smsExpiredMessage) {
        this.smsExpiredMessage = smsExpiredMessage == null ? null : smsExpiredMessage.trim();
    }
}