package com.accumulate.entity;

import java.util.Date;

public class User extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.id
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.name
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.age
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private Short age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.password
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.create_time
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.create_by
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.update_time
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.update_by
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.id
     *
     * @return the value of acc_user.id
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.id
     *
     * @param id the value for acc_user.id
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.name
     *
     * @return the value of acc_user.name
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.name
     *
     * @param name the value for acc_user.name
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.age
     *
     * @return the value of acc_user.age
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.age
     *
     * @param age the value for acc_user.age
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.password
     *
     * @return the value of acc_user.password
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.password
     *
     * @param password the value for acc_user.password
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.create_time
     *
     * @return the value of acc_user.create_time
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.create_time
     *
     * @param createTime the value for acc_user.create_time
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.create_by
     *
     * @return the value of acc_user.create_by
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.create_by
     *
     * @param createBy the value for acc_user.create_by
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.update_time
     *
     * @return the value of acc_user.update_time
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.update_time
     *
     * @param updateTime the value for acc_user.update_time
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.update_by
     *
     * @return the value of acc_user.update_by
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.update_by
     *
     * @param updateBy the value for acc_user.update_by
     *
     * @mbg.generated Wed Jan 04 17:33:16 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}